import type { SiteContent } from './types';

const YOUTUBE = 'https://www.youtube.com/@%EC%B5%9C%EC%9B%90%ED%98%81-b3r';

export const en: SiteContent = {
  meta: {
    title: 'Yin-Yang Five Elements — Choi Won-hyeok Academic Research',
    description: 'Academic research on Donghak, Daesoon thought, and Yin-Yang Five Elements',
  },
  nav: {
    home: 'Home',
    dissertation: 'Dissertations',
    papers: 'Papers',
    books: 'Books',
    yinyang: 'Yin-Yang',
    ai: 'AI',
    homepage: 'Build a Website',
    masters: "Master's Thesis",
    doctoral: 'Doctoral Dissertation',
    visitYoutube: 'Watch on YouTube',
    visitWebsite: 'Visit Website',
    downloadPdf: 'Download PDF',
    comingSoon: 'Coming Soon',
    backToTop: 'Back to List',
    readerDownloads: 'Download Original',
    readerYoutube: 'Watch on YouTube ↗',
    readerPrev: 'Previous',
    readerNext: 'Next',
    readerToc: 'Open contents',
    dissertationDesc: "Master's and Doctoral dissertations",
    papersDesc: 'Journal and conference papers',
    booksDesc: 'Authored books',
    yinyangDesc: 'Yin-Yang Five Elements research and content',
    aiDesc: 'AI usage guides and practical materials',
    homepageDesc: 'A complete guide to building your own website with AI',
  },
  home: {
    heading: '陰陽五行',
    subheading: 'Choi Won-hyeok Academic Research',
    intro: 'Research on endogenous modernity in Donghak and Daesoon thought, circular economic perspective, and the three-dimensional interpretation of Yin-Yang Five Elements.',
  },
  dissertation: {
    doctoral: [
      {
        id: 'doctoral-donghak-daesoon',
        title: 'A Comparative Study of Endogenous Modernity in Donghak and Daesoon Thought',
        subtitle: 'Doctoral Dissertation',
        description: 'A doctoral dissertation comparing and analyzing the endogenous modernity inherent in Donghak and Daesoon thought.',
        youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9xt7bVaB4LcKP9evomr22s',
        websiteUrl: '/en/dissertation/doctoral/donghak-daesoon-en',
      },
    ],
    masters: [
      {
        id: 'masters-daesoon-economy',
        title: "Daesoon Thought's Circular Economic View",
        subtitle: "Master's Thesis",
        description: "A master's thesis studying the circular characteristics of economic thought in Daesoon ideology.",
        youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-qQKkJErG7QrrHCVobzg4X',
        websiteUrl: '/en/dissertation/masters/daesoon-economics-en',
      },
    ],
  },
  papers: [
    {
      id: 'paper-baekchongang',
      title: 'The East Asian Astronomical Significance of the 663 Battle of Baekchon River',
      subtitle: 'Conference Paper',
      description: 'Reading East Asian astronomy through the trifunctional system, this paper reveals the astronomical and historical significance of the five-planet alignment (Oseongchwiru) at the 663 winter solstice — the first Gapja (Gyehae year, Gapja month, day, and hour) — and of the Battle of Baekchon River.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLTiBLx84dYtU',
      websiteUrl: '/en/papers/baekgang-663',
    },
    {
      id: 'paper-search-for-dialogue',
      title: 'Search for Dialogue between Christianity and Islam',
      subtitle: 'Conference Paper',
      description: "A conference paper exploring the possibility of dialogue between Christianity and Islam mediated through Confucianism and Buddhism, drawing on Daesoon Jinri's theory of religion circulation based on Yin-Yang and the Five Elements.",
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLK19Fw9ZnrqI',
      websiteUrl: '/en/papers/search-for-dialogue',
    },
    {
      id: 'paper-jeju-myth-world',
      title: 'A Study on the Possibility of Jeju Mythology as World Mythology',
      subtitle: 'Conference Paper',
      description: 'Centering on the Atlantis myth, this paper explores the possibility of Jeju mythology as a global archetypal mythology through Sundaland, the Budoji, and the Land-of-the-Gentlemen (Gunjaguk) sources.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLff-b7nMmy50',
      websiteUrl: '/en/papers/jeju-myth',
    },
    {
      id: 'paper-kim-jiha',
      title: "A Study of Reconciliation and Coexistence in Kim Ji-ha's Thought",
      subtitle: 'Conference Paper',
      description: "This paper reads the consistency of Kim Ji-ha's thought through liminality and revitalization, comparing the current of reconciliation and coexistence that runs from the life-philosophy of Donghak, through the Yulryeo of Jeongyeok, to the Huingeuneul (White Shadow) aesthetics of Jeungsan.",
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9IghArp0ZbgUa-0Ld2YvxU',
      websiteUrl: '/en/papers/kim-jiha',
    },
    {
      id: 'papers-placeholder',
      title: 'More Papers Coming Soon',
      subtitle: 'Updates forthcoming',
      comingSoon: true,
    },
  ],
  books: [
    {
      id: 'book-ai-survival',
      title: 'Human Survival Strategy through Correlative Thinking and Hwajaeng in the AI Era',
      subtitle: 'Book',
      description: 'A book exploring strategies for human survival in the age of artificial intelligence.',
      youtubeUrl: 'https://youtu.be/Mw-7bXrMgQA',
      websiteUrl: '/en/books/ai-survival',
    },
    {
      id: 'book-jeju-serendipity',
      title: 'Jeju Culture as Serendipity',
      subtitle: 'Book · Jeju Studies Series ⑨',
      description: 'A Jeju studies work exploring why Jeju draws the spotlight, seen through serendipity — the power to turn chance into success. Full English translation, readable online. (Kim Deok-sam & Choi Won-hyeok, 2014)',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLfLEfE_wQTqs',
      websiteUrl: '/en/books/jeju-serendipity',
    },
  ],
  yinyang: [
    {
      id: 'yinyang-3d',
      title: 'Three-Dimensional Five Elements',
      subtitle: 'Yin-Yang Five Elements',
      description: 'Research on the three-dimensional interpretation and modern application of Yin-Yang Five Elements.',
      youtubeUrl: YOUTUBE,
    },
  ],
  ai: {
    homepage: [
      {
        id: 'ai-homepage-guide',
        title: 'A Complete 6-Step Guide to Building a Website — Even for Beginners (Full)',
        subtitle: 'AI · Build a Website · Full Guide',
        description: 'From buying a domain to configuring Vercel, GitHub, Obsidian, and Google Drive, then installing Claude Code and building and deploying your site — a complete 6-step guide any beginner can follow (Korean).',
        pdfUrl: '/pdf/website-guide-ko.pdf',
        youtubeUrl: 'https://youtu.be/5L5IP7iyvko',
      },
      {
        id: 'ai-homepage-ch00',
        title: '00. Introduction · Overall Flow',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'The introductory chapter that walks through the overall flow of the 6-step website-building guide (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch00.pdf',
        youtubeUrl: 'https://youtu.be/qQfcldWYc-E',
      },
      {
        id: 'ai-homepage-ch01',
        title: '01. Whois · Buying a Domain',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'Step-by-step guide to searching and buying your own domain on Whois (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch01.pdf',
      },
      {
        id: 'ai-homepage-ch02',
        title: '02. Sign up for Vercel',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'How to sign up for the Vercel deployment platform and complete the initial setup (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch02.pdf',
      },
      {
        id: 'ai-homepage-ch03',
        title: '03. Sign up for GitHub',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'How to sign up for GitHub and prepare your source-code repository (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch03.pdf',
      },
      {
        id: 'ai-homepage-ch04',
        title: '04. Using Obsidian',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'How to install and use the Obsidian note-taking and writing tool (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch04.pdf',
      },
      {
        id: 'ai-homepage-ch05',
        title: '05. Using Google Drive',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'How to use Google Drive as a working space alongside your site (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch05.pdf',
      },
      {
        id: 'ai-homepage-ch06a',
        title: '06a. Installing Claude Code',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'How to install the Claude Code CLI and complete the initial login/authentication (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch06a.pdf',
      },
      {
        id: 'ai-homepage-ch06b',
        title: '06b. Claude Code · Building & Deploying the Site',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'The full workflow for building the actual site with Claude Code and deploying it to Vercel (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch06b.pdf',
      },
      {
        id: 'ai-homepage-ch07',
        title: '07. Appendix · Commands & Costs',
        subtitle: 'AI · Build a Website · Chapter-by-Chapter',
        description: 'Appendix summarizing frequently used commands and the cost of each service (Korean).',
        pdfUrl: '/pdf/website-guide-ko-ch07.pdf',
      },
    ],
  },
};
