import type { SiteContent } from './types';

const YOUTUBE = 'https://www.youtube.com/@%EC%B5%9C%EC%9B%90%ED%98%81-b3r';

export const ja: SiteContent = {
  meta: {
    title: '陰陽五行 — 崔元赫学術研究',
    description: '東学思想、大巡思想、陰陽五行に関する学術研究',
  },
  nav: {
    home: 'ホーム',
    dissertation: '学位論文',
    papers: '発表論文',
    books: '単行本',
    yinyang: '陰陽五行',
    ai: 'AI',
    homepage: 'ホームページ作成',
    masters: '修士論文',
    doctoral: '博士論文',
    visitYoutube: 'YouTubeで見る',
    visitWebsite: 'ウェブサイトへ',
    downloadPdf: 'PDFダウンロード',
    comingSoon: '近日公開',
    backToTop: '一覧へ戻る',
    readerDownloads: '原文をダウンロード',
    readerYoutube: 'YouTubeで見る ↗',
    readerPrev: '前へ',
    readerNext: '次へ',
    readerToc: '目次を開く',
    dissertationDesc: '修士・博士学位論文',
    papersDesc: '学術誌・学会発表論文',
    booksDesc: '単著書籍',
    yinyangDesc: '陰陽五行関連研究・コンテンツ',
    aiDesc: 'AI活用ガイドと実践資料',
    homepageDesc: 'AIで自分のホームページを作る完全ガイド',
  },
  home: {
    heading: '陰陽五行',
    subheading: '崔元赫学術研究',
    intro: '東学思想と大巡思想の自生的近代性、循環的経済観、陰陽五行の立体的解釈を研究します。',
  },
  dissertation: {
    doctoral: [
      {
        id: 'doctoral-donghak-daesoon',
        title: '東学思想と大巡思想の自生的近代性比較研究',
        subtitle: '博士学位論文',
        description: '東学思想と大巡思想に内在する自生的近代性を比較分析した博士学位論文。',
        youtubeUrl: YOUTUBE,
        websiteUrl: '/ja/dissertation/doctoral/donghak-daesoon-ja',
      },
    ],
    masters: [
      {
        id: 'masters-daesoon-economy',
        title: '大巡思想の循環的経済観',
        subtitle: '修士学位論文',
        description: '大巡思想における経済思想の循環的特性を研究した修士学位論文。',
        youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-qQKkJErG7QrrHCVobzg4X',
        websiteUrl: '/ja/dissertation/masters/daesoon-economics-ja',
      },
    ],
  },
  papers: [
    {
      id: 'paper-baekchongang',
      title: '663年 白村江の戦いの東洋天文学的意義',
      subtitle: '発表論文',
      description: '三機能体系によって東洋天文学を読み解き、最初の甲子（癸亥年・甲子月・甲子日・甲子時）にあたる663年冬至の五星聚婁と、白村江の戦いが持つ天文学的・歴史的意義を明らかにした発表論文。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLL3m0fhP-3JU',
      websiteUrl: '/ja/papers/baekgang-663',
    },
    {
      id: 'paper-search-for-dialogue',
      title: 'キリスト教とイスラム教の対話の模索',
      subtitle: '発表論文',
      description: '陰陽五行に基づく大巡真理の宗教循環論を用い、儒教・仏教を媒介としてキリスト教とイスラム教の対話の可能性を模索した発表論文。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLaR4liIoO26s',
      websiteUrl: '/ja/papers/search-for-dialogue',
    },
    {
      id: 'paper-jeju-myth-world',
      title: '世界神話としての済州神話の可能性に関する研究',
      subtitle: '発表論文',
      description: 'アトランティス神話を中心に、スンダランド・『符都誌』・君子国の文献を通じて、済州神話が世界の原型神話となりうる可能性を探った論文。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLX9Ikms9qREg',
      websiteUrl: '/ja/papers/jeju-myth',
    },
    {
      id: 'paper-kim-jiha',
      title: '金芝河思想に現れた和解と相生の研究',
      subtitle: '発表論文',
      description: '本稿は金芝河思想の一貫性をリミナリティとリバイタライゼーションで読み解き、東学の生命思想・正易の律呂・甑山のヒングヌル（白い翳）美学へと連なる和解と相生の流れを比較した論文である。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9IghArp0ZbgUa-0Ld2YvxU',
      websiteUrl: '/ja/papers/kim-jiha',
    },
    {
      id: 'papers-placeholder',
      title: 'その他の発表論文 近日公開',
      subtitle: '更新予定',
      comingSoon: true,
    },
  ],
  books: [
    {
      id: 'book-ai-survival',
      title: 'AI時代における相関的思惟と和諍による人類の生存戦略',
      subtitle: '単行本',
      description: 'AI時代における人間の生存戦略を探求した著書。',
      youtubeUrl: 'https://youtu.be/i51ncE2NORk',
      websiteUrl: '/ja/books/ai-survival',
    },
    {
      id: 'book-jeju-serendipity',
      title: 'セレンディピティとしての済州文化',
      subtitle: '単行本 · 済州学叢書 ⑨',
      description: '偶然を成功へ導く力＝セレンディピティの視点から、済州が脚光を浴びる理由を探る済州学の研究書。日本語全訳をオンラインで読めます。（金徳三・崔元爀 共著、2014年）',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLf-LvaN16i7g',
      websiteUrl: '/ja/books/jeju-serendipity',
    },
  ],
  yinyang: [
    {
      id: 'yinyang-3d',
      title: '立体五行',
      subtitle: '陰陽五行',
      description: '陰陽五行の立体的解釈と現代的応用に関する研究。',
      youtubeUrl: YOUTUBE,
    },
  ],
  ai: {
    homepage: [
      {
        id: 'ai-homepage-guide',
        title: 'パソコン初心者でも作れるウェブサイト6ステップ完全ガイド(全体版)',
        subtitle: 'AI · ホームページ作成 · 全体版',
        description: 'ドメイン購入から Vercel・GitHub・Obsidian・Google Drive の設定、Claude Code のインストール、サイト制作・デプロイまでを6ステップにまとめた完全ガイド(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko.pdf',
        youtubeUrl: 'https://youtu.be/5L5IP7iyvko',
      },
      {
        id: 'ai-homepage-ch00',
        title: '00. 紹介 · 全体の流れ',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'ウェブサイト構築6ステップガイドの全体の流れを最初に整理する導入章(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch00.pdf',
        youtubeUrl: 'https://youtu.be/qQfcldWYc-E',
      },
      {
        id: 'ai-homepage-ch01',
        title: '01. Whois · ドメイン購入',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'Whois で自分のドメインを検索・購入する手順を解説(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch01.pdf',
      },
      {
        id: 'ai-homepage-ch02',
        title: '02. Vercel 登録',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'デプロイプラットフォーム Vercel の登録と初期設定の手順(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch02.pdf',
      },
      {
        id: 'ai-homepage-ch03',
        title: '03. GitHub 登録',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'ソースコードホスティング GitHub の登録とリポジトリ準備の手順(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch03.pdf',
      },
      {
        id: 'ai-homepage-ch04',
        title: '04. Obsidian 活用',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'ノート・執筆ツール Obsidian のインストールと使い方(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch04.pdf',
      },
      {
        id: 'ai-homepage-ch05',
        title: '05. Google Drive 活用',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'Google Drive を作業スペースとして活用する方法(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch05.pdf',
      },
      {
        id: 'ai-homepage-ch06a',
        title: '06a. Claude Code インストール',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'Claude Code CLI のインストールと初回ログイン・認証の手順(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch06a.pdf',
      },
      {
        id: 'ai-homepage-ch06b',
        title: '06b. Claude Code · サイト制作・デプロイ',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'Claude Code で実際にサイトを制作し Vercel にデプロイするまでの全工程(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch06b.pdf',
      },
      {
        id: 'ai-homepage-ch07',
        title: '07. 付録 · コマンドと費用',
        subtitle: 'AI · ホームページ作成 · 章別ガイド',
        description: 'よく使うコマンドと各サービスの費用をまとめた付録(韓国語版)。',
        pdfUrl: '/pdf/website-guide-ko-ch07.pdf',
      },
    ],
  },
};
