import type { SiteContent } from './types';

const YOUTUBE = 'https://www.youtube.com/@%EC%B5%9C%EC%9B%90%ED%98%81-b3r';

export const ko: SiteContent = {
  meta: {
    title: '음양오행 — 최원혁 학술연구',
    description: '동학사상, 대순사상, 음양오행에 관한 학술연구 및 저작물',
  },
  nav: {
    home: '홈',
    dissertation: '학위논문',
    papers: '발표논문',
    books: '단행본',
    yinyang: '음양오행',
    masters: '석사논문',
    doctoral: '박사논문',
    visitYoutube: '유튜브 보기',
    visitWebsite: '홈페이지 방문',
    comingSoon: '준비 중',
    backToTop: '목록으로',
    dissertationDesc: '석사 및 박사 학위논문',
    papersDesc: '학술지 및 학술대회 발표논문',
    booksDesc: '단독 저술 단행본',
    yinyangDesc: '음양오행 관련 연구 및 콘텐츠',
  },
  home: {
    heading: '陰陽五行',
    subheading: '최원혁 학술연구',
    intro: '동학사상과 대순사상의 자생적 근대성, 순환적 경제관, 음양오행의 입체적 해석을 연구합니다.',
  },
  dissertation: {
    doctoral: [
      {
        id: 'doctoral-donghak-daesoon',
        title: '동학사상과 대순사상의 자생적근대성 비교 연구',
        subtitle: '박사학위논문',
        description: '동학사상과 대순사상에 내재된 자생적 근대성을 비교 분석한 박사학위논문입니다.',
        youtubeUrl: YOUTUBE,
        websiteUrl: '/ko/dissertation/doctoral/donghak-daesoon-ko',
      },
    ],
    masters: [
      {
        id: 'masters-daesoon-economy',
        title: '대순사상의 순환적 경제관',
        subtitle: '석사학위논문',
        description: '대순사상에 나타난 경제 사상의 순환적 특성을 연구한 석사학위논문입니다.',
        youtubeUrl: YOUTUBE,
        websiteUrl: 'https://daesoon-web.vercel.app/chapter/3',
      },
    ],
  },
  papers: [
    {
      id: 'paper-baekchongang',
      title: '663년 백촌강 전투의 동양 천문학적 의의',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-search-for-dialogue',
      title: 'Search for Dialogue',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-dangun-economy',
      title: '경제사상으로서의 단군사상과 서양 한류',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-geumgangsan',
      title: '금강산 어원과 담무갈보살, 회암사 유래 추적',
      subtitle: '발표논문',
      description: '금강산의 어원을 화엄경 담무갈보살 전승과 수미산 이론으로 추적하고, 회암사 중창의 배경을 가야·서북공정의 새로운 단서들과 함께 살펴본 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN_M77BOYbITNGpzA4Pxyoc5',
      websiteUrl: '/ko/papers/geumgangsan',
    },
    {
      id: 'paper-kim-jiha',
      title: '김지하 사상에 나타난 화해와 상생',
      subtitle: '발표논문',
      description: '김지하 사상의 일관성을 리미널리티·리바이탈라이제이션으로 풀고, 동학의 생명·정역의 율려·증산의 흰그늘 미학으로 이어지는 화해와 상생의 흐름을 비교한 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9IghArp0ZbgUa-0Ld2YvxU',
      websiteUrl: '/ko/papers/kim-jiha',
    },
    {
      id: 'paper-sacred-numbers',
      title: '단군-미트라-미륵신화에 나타난 성수(聖數)',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-dangjin-maritime',
      title: '당진(唐津) 이용후생(利用厚生) 해양(海洋)문화의 배경 -백촌강전투 백제부흥군의 기억유산과 관련하여-',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-daesoon-capitalism-alternative',
      title: '대순사상의 천지 개념에 나타난 종교로서의 자본주의에 대한 대안',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-daejin-liminality',
      title: '한국 자생종교에 나타난 동아시아의 자생적 근대성 연구',
      subtitle: '발표논문',
      description: '동학사상과 대순사상의 상생적 삼계관을 중심으로, 한국 자생종교의 자생적 근대성을 리미널리티 이론으로 풀어낸 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-f_AEhSlun0hBRifiMVfV2',
      websiteUrl: '/ko/papers/liminality',
    },
    {
      id: 'paper-dongi',
      title: '두 개의 동이족에 대한 이견(異見)',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-literary-therapy',
      title: '문학치료의 기호 논리적 접근',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-samgang-oryun',
      title: '삼강오륜 출현의 스토리텔링적 배경',
      subtitle: '발표논문',
      description: '동중서의 삼강오륜을 재이설·상수학·칠성 신앙의 스토리텔링적 출현 배경에서 분석하고 캠벨의 원질신화 이론과 비교한 논문입니다.',
      youtubeUrl: 'https://youtu.be/X46pTTNjCMA',
      websiteUrl: '/ko/papers/samgang-oryun',
    },
    {
      id: 'paper-jeju-myth-world',
      title: '세계 신화로서의 제주 신화 가능성 연구',
      subtitle: '발표논문',
      description: '아틀란티스 신화를 중심으로, 순다랜드·『부도지』·군자국 문헌을 통해 제주신화의 세계 원형신화로서의 가능성을 모색한 논문입니다.',
      youtubeUrl: 'https://youtube.com/playlist?list=PLW3dzK2lgZM0&si=lH8mdvJuSBJMXD_U',
      websiteUrl: '/ko/papers/jeju-myth',
    },
    {
      id: 'paper-kungfu-panda',
      title: '영화 「쿵푸팬더 4」에 나타난 동서양 성장심리 비교',
      subtitle: '발표논문',
      description: '대상-관계이론·라깡 4담론·매슬로우 욕구설과 삼강오륜·욕계·12운성·천지인 미학을 교차시켜 『쿵푸팬더』 시리즈의 동서양 성장심리 통합 모델을 모색한 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN8FmvHHUCqxrSTWT9JTPzLo',
      websiteUrl: '/ko/papers/kungfu-panda',
    },
    {
      id: 'paper-jeju-regional-archetype',
      title: '제주도를 중심으로 본 동아시아의 지역 원형',
      subtitle: '발표논문',
      description: '월지족의 이동 경로와 관련하여 제주도의 고인돌·삼성혈·서복·돌하르방·고산리 토기를 동아시아 지역 원형의 표지로 재해석한 논문입니다.',
      youtubeUrl: 'https://youtube.com/playlist?list=PLw9IxWay4JN-ikwRiBum5qv9YMprsIBIg&si=7h9SFmSu-y9bpnzh',
      websiteUrl: '/ko/papers/jeju-archetype',
    },
    {
      id: 'paper-yijing-comparative',
      title: '주역의 동서비교종교학적 이해 -지젝과 나카자와 신이치 종교이론에 나타난 삼기능체계를 중심으로-',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-jinmuk-won',
      title: '진묵의 원에 대한 연구',
      subtitle: '발표논문',
      description: '진묵(震默)이 품은 원(寃)의 성격과 크기를 서가여래의 오백대원, 나반존자·나반-아만, 음양오행의 관점에서 고찰한 논문입니다.',
      youtubeUrl: 'https://youtu.be/9E_p0Exm3EI',
      websiteUrl: '/ko/papers/jinmuk-won',
    },
    {
      id: 'paper-cham-donghak',
      title: '참동학의 미래전망  -동학사상과 대순사상의 비교를 중심으로-',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-taejo-yi-seonggye',
      title: '태조 이성계의 동아시아 갈등에 대한 화해 의지',
      subtitle: '발표논문',
      description: '조선 건국을 사대주의·내부권력투쟁의 트라우마가 아닌 태조 이성계의 동아시아 갈등 화해 의지로 재조명하고, 포천 전장·과전법과 회암사 중창을 사례로 살펴본 논문입니다.',
      youtubeUrl: 'https://youtu.be/roAeRzY1VN8',
      websiteUrl: '/ko/papers/taejo',
    },
    {
      id: 'paper-postcorona-body',
      title: '포스트코로나시대 신종교의 대안적 인체관 일고찰--대순사상과 휴먼디자인을 중심으로-',
      subtitle: '발표논문',
      description: '트랜스휴머니즘·포스트휴머니즘에 맞서, 혼백결합·신인소통·집단치유·우주확장이라는 네 인체관을 대순사상과 휴먼디자인을 중심으로 살펴본 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9iNSbb9OAnzPioCzOmAN61',
      websiteUrl: '/ko/papers/postcorona',
    },
    {
      id: 'paper-mireuk-origin',
      title: '한국 미륵신앙의 기원에 대한 일고찰  미트라와 스키타이를 중심으로',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-korean-new-religion-modernity',
      title: '한국 신종교의 현대성에 대한 일고찰',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    // 발표논문을 추가하려면 아래 형식으로 항목을 추가하세요:
    // {
    //   id: 'paper-고유ID',
    //   title: '논문 제목',
    //   subtitle: '게재지 또는 학술대회명',
    //   description: '논문 요약',
    //   youtubeUrl: '유튜브 재생목록 URL',
    //   websiteUrl: '논문 홈페이지 URL',
    // },
  ],
  books: [
    {
      id: 'book-ai-survival',
      title: 'AI시대 상관적 사유와 화쟁을 통한 인류의 생존전략',
      subtitle: '단행본 · 가설과상상총서 ①',
      description: 'AI 시대에 입체(立體)·순환(循環)·공감(共感)·융합(融合)의 4가지 상관적 사유와 원효의 화쟁이론을 통해 인류의 생존 전략을 탐구한 저서입니다.',
      youtubeUrl: YOUTUBE,
      websiteUrl: '/ko/books/ai-survival',
    },
    // 단행본을 추가하려면 아래 형식으로 항목을 추가하세요:
    // {
    //   id: 'book-고유ID',
    //   title: '도서 제목',
    //   subtitle: '단행본',
    //   description: '도서 소개',
    //   youtubeUrl: '유튜브 URL',
    //   websiteUrl: '도서 홈페이지 URL',
    // },
  ],
  yinyang: [
    {
      id: 'yinyang-3d',
      title: '입체오행',
      subtitle: '음양오행',
      description: '음양오행의 입체적 해석과 현대적 적용에 관한 연구입니다.',
      youtubeUrl: YOUTUBE,
    },
    // 음양오행 항목을 추가하려면 아래 형식으로 항목을 추가하세요:
    // {
    //   id: 'yinyang-고유ID',
    //   title: '항목 제목',
    //   subtitle: '음양오행',
    //   description: '설명',
    //   youtubeUrl: '유튜브 URL',
    //   websiteUrl: '홈페이지 URL',
    // },
  ],
};
