import type { SiteContent } from './types';

const YOUTUBE = 'https://www.youtube.com/@%EC%B5%9C%EC%9B%90%ED%98%81-b3r';

export const ko: SiteContent = {
  meta: {
    title: '음양오행 — 최원혁 학술연구',
    description: '동학사상, 대순사상, 음양오행에 관한 학술연구 및 저작물',
  },
  nav: {
    home: '홈',
    dissertation: '학위논문',
    papers: '발표논문',
    books: '단행본',
    yinyang: '음양오행',
    ai: 'AI',
    homepage: '홈페이지 만들기',
    masters: '석사논문',
    doctoral: '박사논문',
    visitYoutube: '유튜브 보기',
    visitWebsite: '홈페이지 방문',
    downloadPdf: 'PDF 다운로드',
    comingSoon: '준비 중',
    backToTop: '목록으로',
    readerDownloads: '원문 다운로드',
    readerYoutube: '유튜브 보기 ↗',
    readerPrev: '이전',
    readerNext: '다음',
    readerToc: '목차 열기',
    dissertationDesc: '석사 및 박사 학위논문',
    papersDesc: '학술지 및 학술대회 발표논문',
    booksDesc: '단독 저술 단행본',
    yinyangDesc: '음양오행 관련 연구 및 콘텐츠',
    aiDesc: 'AI 활용 가이드 및 실습 자료',
    homepageDesc: 'AI로 나만의 홈페이지 만들기 완벽 가이드',
  },
  home: {
    heading: '陰陽五行',
    subheading: '최원혁 학술연구',
    intro: '동학사상과 대순사상의 자생적 근대성, 순환적 경제관, 음양오행의 입체적 해석을 연구합니다.',
  },
  dissertation: {
    doctoral: [
      {
        id: 'doctoral-donghak-daesoon',
        title: '동학사상과 대순사상의 자생적근대성 비교 연구',
        subtitle: '박사학위논문',
        description: '동학사상과 대순사상에 내재된 자생적 근대성을 비교 분석한 박사학위논문입니다.',
        youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-f_AEhSlun0hBRifiMVfV2',
        websiteUrl: '/ko/dissertation/doctoral/donghak-daesoon-ko',
      },
    ],
    masters: [
      {
        id: 'masters-daesoon-economy',
        title: '대순사상의 순환적 경제관',
        subtitle: '석사학위논문',
        description: '대순사상에 나타난 경제 사상의 순환적 특성을 연구한 석사학위논문입니다.',
        youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-qQKkJErG7QrrHCVobzg4X',
        websiteUrl: '/ko/dissertation/masters/daesoon-economics-ko',
      },
    ],
  },
  papers: [
    {
      id: 'paper-baekchongang',
      title: '663년 백촌강 전투의 동양 천문학적 의의',
      subtitle: '발표논문',
      description: '삼기능체계로 동양천문학을 읽어, 최초의 갑자(계해년 갑자월 갑자일 갑자시)인 663년 동지의 오성취루와 백촌강 전투가 갖는 천문학적·역사적 의의를 밝힌 발표논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-KuvpeGhV88_gRj61UCP4_',
      websiteUrl: '/ko/papers/baekgang-663',
    },
    {
      id: 'paper-search-for-dialogue',
      title: 'Search for Dialogue',
      subtitle: '발표논문',
      description: '음양오행에 기반한 대순진리의 종교 순환론으로, 유교·불교를 매개 삼아 기독교와 이슬람의 대화 가능성을 모색한 발표논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLObdwEym8K1c',
      websiteUrl: '/ko/papers/search-for-dialogue',
    },
    {
      id: 'paper-dangun-economy',
      title: '경제사상으로서의 단군사상과 서양 한류',
      subtitle: '발표논문',
      description: '한류의 도덕적 배경을 단군사상에 연계하여, 홍익인간·재세이화의 경제사상(삼수분화·입체오행)과 서양 한류의 역사로 규명한 발표논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN_Q3100PlwmezrKMLUyD01Q',
      websiteUrl: '/ko/papers/dangun-economy',
    },
    {
      id: 'paper-geumgangsan',
      title: '금강산 어원과 담무갈보살, 회암사 유래 추적',
      subtitle: '발표논문',
      description: '금강산의 어원을 화엄경 담무갈보살 전승과 수미산 이론으로 추적하고, 회암사 중창의 배경을 가야·서북공정의 새로운 단서들과 함께 살펴본 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN_M77BOYbITNGpzA4Pxyoc5',
      websiteUrl: '/ko/papers/geumgangsan',
    },
    {
      id: 'paper-kim-jiha',
      title: '김지하 사상에 나타난 화해와 상생',
      subtitle: '발표논문',
      description: '김지하 사상의 일관성을 리미널리티·리바이탈라이제이션으로 풀고, 동학의 생명·정역의 율려·증산의 흰그늘 미학으로 이어지는 화해와 상생의 흐름을 비교한 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9IghArp0ZbgUa-0Ld2YvxU',
      websiteUrl: '/ko/papers/kim-jiha',
    },
    {
      id: 'paper-sacred-numbers',
      title: '단군-미트라-미륵신화에 나타난 성수(聖數)',
      subtitle: '발표논문',
      description: '단군·미트라·미륵신화에 공통으로 나타나는 성수(聖數) 3과 7을, 조셉 캠벨의 단일신화와 나카자와 신이치의 프랙탈 신화이론을 매개로 창세 원리와 칠성·삼신의 구조로 비교한 발표논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9XYG6jZ4vxT_umJ8VRYk5x',
      websiteUrl: '/ko/papers/sacred-numbers',
    },
    {
      id: 'paper-dangjin-maritime',
      title: '당진(唐津) 이용후생(利用厚生) 해양(海洋)문화의 배경 -백촌강전투 백제부흥군의 기억유산과 관련하여-',
      subtitle: '발표논문',
      description: '당진(唐津)의 이용후생 해양문화 배경을 백촌강 전투와 백제부흥군의 기억유산으로 재해석하고, 예맥족 디아스포라와 전투 이후의 미륵 불교·해양 상업문화를 동아시아 트라우마의 관점에서 조명한 발표논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN8RJ1_-bYtR5kVrSDQ2dvwV',
      websiteUrl: '/ko/papers/dangjin',
    },
    {
      id: 'paper-daesoon-capitalism-alternative',
      title: '대순사상의 천지 개념에 나타난 종교로서의 자본주의에 대한 대안',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-daejin-liminality',
      title: '한국 자생종교에 나타난 동아시아의 자생적 근대성 연구',
      subtitle: '발표논문',
      description: '동학사상과 대순사상의 상생적 삼계관을 중심으로, 한국 자생종교의 자생적 근대성을 리미널리티 이론으로 풀어낸 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-f_AEhSlun0hBRifiMVfV2',
      websiteUrl: '/ko/papers/liminality',
    },
    {
      id: 'paper-dongi',
      title: '두 개의 동이족에 대한 이견(異見)',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-literary-therapy',
      title: '문학치료의 기호 논리적 접근',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-samgang-oryun',
      title: '삼강오륜 출현의 스토리텔링적 배경',
      subtitle: '발표논문',
      description: '동중서의 삼강오륜을 재이설·상수학·칠성 신앙의 스토리텔링적 출현 배경에서 분석하고 캠벨의 원질신화 이론과 비교한 논문입니다.',
      youtubeUrl: 'https://youtu.be/X46pTTNjCMA',
      websiteUrl: '/ko/papers/samgang-oryun',
    },
    {
      id: 'paper-jeju-myth-world',
      title: '세계 신화로서의 제주 신화 가능성 연구',
      subtitle: '발표논문',
      description: '아틀란티스 신화를 중심으로, 순다랜드·『부도지』·군자국 문헌을 통해 제주신화의 세계 원형신화로서의 가능성을 모색한 논문입니다.',
      youtubeUrl: 'https://youtube.com/playlist?list=PLW3dzK2lgZM0&si=lH8mdvJuSBJMXD_U',
      websiteUrl: '/ko/papers/jeju-myth',
    },
    {
      id: 'paper-kungfu-panda',
      title: '영화 「쿵푸팬더 4」에 나타난 동서양 성장심리 비교',
      subtitle: '발표논문',
      description: '대상-관계이론·라깡 4담론·매슬로우 욕구설과 삼강오륜·욕계·12운성·천지인 미학을 교차시켜 『쿵푸팬더』 시리즈의 동서양 성장심리 통합 모델을 모색한 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN8FmvHHUCqxrSTWT9JTPzLo',
      websiteUrl: '/ko/papers/kungfu-panda',
    },
    {
      id: 'paper-jeju-regional-archetype',
      title: '제주도를 중심으로 본 동아시아의 지역 원형',
      subtitle: '발표논문',
      description: '월지족의 이동 경로와 관련하여 제주도의 고인돌·삼성혈·서복·돌하르방·고산리 토기를 동아시아 지역 원형의 표지로 재해석한 논문입니다.',
      youtubeUrl: 'https://youtube.com/playlist?list=PLw9IxWay4JN-ikwRiBum5qv9YMprsIBIg&si=7h9SFmSu-y9bpnzh',
      websiteUrl: '/ko/papers/jeju-archetype',
    },
    {
      id: 'paper-yijing-comparative',
      title: '주역의 동서비교종교학적 이해 -지젝과 나카자와 신이치 종교이론에 나타난 삼기능체계를 중심으로-',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-jinmuk-won',
      title: '진묵의 원에 대한 연구',
      subtitle: '발표논문',
      description: '진묵(震默)이 품은 원(寃)의 성격과 크기를 서가여래의 오백대원, 나반존자·나반-아만, 음양오행의 관점에서 고찰한 논문입니다.',
      youtubeUrl: 'https://youtu.be/9E_p0Exm3EI',
      websiteUrl: '/ko/papers/jinmuk-won',
    },
    {
      id: 'paper-cham-donghak',
      title: '참동학의 미래전망  -동학사상과 대순사상의 비교를 중심으로-',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-taejo-yi-seonggye',
      title: '태조 이성계의 동아시아 갈등에 대한 화해 의지',
      subtitle: '발표논문',
      description: '조선 건국을 사대주의·내부권력투쟁의 트라우마가 아닌 태조 이성계의 동아시아 갈등 화해 의지로 재조명하고, 포천 전장·과전법과 회암사 중창을 사례로 살펴본 논문입니다.',
      youtubeUrl: 'https://youtu.be/roAeRzY1VN8',
      websiteUrl: '/ko/papers/taejo',
    },
    {
      id: 'paper-postcorona-body',
      title: '포스트코로나시대 신종교의 대안적 인체관 일고찰--대순사상과 휴먼디자인을 중심으로-',
      subtitle: '발표논문',
      description: '트랜스휴머니즘·포스트휴머니즘에 맞서, 혼백결합·신인소통·집단치유·우주확장이라는 네 인체관을 대순사상과 휴먼디자인을 중심으로 살펴본 논문입니다.',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9iNSbb9OAnzPioCzOmAN61',
      websiteUrl: '/ko/papers/postcorona',
    },
    {
      id: 'paper-mireuk-origin',
      title: '한국 미륵신앙의 기원에 대한 일고찰  미트라와 스키타이를 중심으로',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    {
      id: 'paper-korean-new-religion-modernity',
      title: '한국 신종교의 현대성에 대한 일고찰',
      subtitle: '발표논문',
      youtubeUrl: YOUTUBE,
    },
    // 발표논문을 추가하려면 아래 형식으로 항목을 추가하세요:
    // {
    //   id: 'paper-고유ID',
    //   title: '논문 제목',
    //   subtitle: '게재지 또는 학술대회명',
    //   description: '논문 요약',
    //   youtubeUrl: '유튜브 재생목록 URL',
    //   websiteUrl: '논문 홈페이지 URL',
    // },
  ],
  books: [
    {
      id: 'book-ai-survival',
      title: 'AI시대 상관적 사유와 화쟁을 통한 인류의 생존전략',
      subtitle: '단행본 · 가설과상상총서 ①',
      description: 'AI 시대에 입체(立體)·순환(循環)·공감(共感)·융합(融合)의 4가지 상관적 사유와 원효의 화쟁이론을 통해 인류의 생존 전략을 탐구한 저서입니다.',
      youtubeUrl: 'https://youtu.be/2FBhUTRkhR0',
      websiteUrl: '/ko/books/ai-survival',
    },
    {
      id: 'book-jeju-serendipity',
      title: '세렌디피티로서의 제주문화',
      subtitle: '단행본 · 제주학총서 ⑨',
      description: '제주가 각광받는 이유를 세렌디피티(우연을 성공으로 이끄는 힘)의 관점에서 탐구한 제주학 연구서입니다. (김덕삼·최원혁 공저, 2014)',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN_V_IRxyxJonhOIHVX22r66',
      websiteUrl: '/ko/books/jeju-serendipity',
    },
    // 단행본을 추가하려면 아래 형식으로 항목을 추가하세요:
    // {
    //   id: 'book-고유ID',
    //   title: '도서 제목',
    //   subtitle: '단행본',
    //   description: '도서 소개',
    //   youtubeUrl: '유튜브 URL',
    //   websiteUrl: '도서 홈페이지 URL',
    // },
  ],
  yinyang: [
    {
      id: 'yinyang-3d',
      title: '입체오행',
      subtitle: '음양오행',
      description: '음양오행의 입체적 해석과 현대적 적용에 관한 연구입니다.',
      youtubeUrl: YOUTUBE,
    },
    // 음양오행 항목을 추가하려면 아래 형식으로 항목을 추가하세요:
    // {
    //   id: 'yinyang-고유ID',
    //   title: '항목 제목',
    //   subtitle: '음양오행',
    //   description: '설명',
    //   youtubeUrl: '유튜브 URL',
    //   websiteUrl: '홈페이지 URL',
    // },
  ],
  ai: {
    homepage: [
      {
        id: 'ai-homepage-guide',
        title: '컴맹도 만드는 웹사이트 6단계 완벽 가이드 (전체)',
        subtitle: 'AI · 홈페이지 만들기 · 전체본',
        description: '도메인 구입부터 Vercel·GitHub·Obsidian·Google Drive 설정, Claude Code 설치와 사이트 제작·배포까지 컴맹도 따라할 수 있도록 6단계로 정리한 완벽 가이드입니다.',
        pdfUrl: '/pdf/website-guide-ko.pdf',
        youtubeUrl: 'https://youtu.be/5L5IP7iyvko',
      },
      {
        id: 'ai-homepage-ch00',
        title: '00. 소개 · 전체흐름',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: '컴맹도 만드는 웹사이트 6단계 가이드의 전체 흐름을 먼저 짚어보는 소개 장입니다.',
        pdfUrl: '/pdf/website-guide-ko-ch00.pdf',
        youtubeUrl: 'https://youtu.be/qQfcldWYc-E',
      },
      {
        id: 'ai-homepage-ch01',
        title: '01. 후이즈 · 도메인 구입',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: '후이즈(Whois)에서 나만의 도메인을 검색하고 구입하는 방법을 단계별로 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch01.pdf',
      },
      {
        id: 'ai-homepage-ch02',
        title: '02. Vercel 가입',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: '배포 플랫폼 Vercel에 가입하고 초기 설정하는 방법을 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch02.pdf',
      },
      {
        id: 'ai-homepage-ch03',
        title: '03. GitHub 가입',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: '소스 코드 저장소 GitHub 가입과 저장소 준비 방법을 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch03.pdf',
      },
      {
        id: 'ai-homepage-ch04',
        title: '04. Obsidian 사용',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: '메모·집필 도구 Obsidian 설치와 활용법을 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch04.pdf',
      },
      {
        id: 'ai-homepage-ch05',
        title: '05. Google Drive 사용',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: 'Google Drive를 작업 공간으로 활용하는 방법을 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch05.pdf',
      },
      {
        id: 'ai-homepage-ch06a',
        title: '06a. Claude Code 설치',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: 'Claude Code CLI 설치와 초기 로그인·인증 과정을 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch06a.pdf',
      },
      {
        id: 'ai-homepage-ch06b',
        title: '06b. Claude Code · 사이트 제작·배포',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: 'Claude Code로 실제 사이트를 만들고 Vercel에 배포하는 전 과정을 안내합니다.',
        pdfUrl: '/pdf/website-guide-ko-ch06b.pdf',
      },
      {
        id: 'ai-homepage-ch07',
        title: '07. 부록 · 명령어와 비용',
        subtitle: 'AI · 홈페이지 만들기 · 장별 가이드',
        description: '자주 쓰는 명령어 정리와 각 서비스 비용을 정리한 부록입니다.',
        pdfUrl: '/pdf/website-guide-ko-ch07.pdf',
      },
      // AI 홈페이지 자료를 추가하려면 아래 형식으로 항목을 추가하세요:
      // {
      //   id: 'ai-homepage-고유ID',
      //   title: '자료 제목',
      //   subtitle: 'AI · 홈페이지 만들기',
      //   description: '자료 소개',
      //   pdfUrl: '/pdf/파일명.pdf',
      //   youtubeUrl: '유튜브 URL',
      // },
    ],
  },
};
