import type { SiteContent } from './types';

const YOUTUBE = 'https://www.youtube.com/@%EC%B5%9C%EC%9B%90%ED%98%81-b3r';

export const zh: SiteContent = {
  meta: {
    title: '阴阳五行 — 崔元赫学术研究',
    description: '关于东学思想、大巡思想和阴阳五行的学术研究',
  },
  nav: {
    home: '首页',
    dissertation: '学位论文',
    papers: '发表论文',
    books: '单行本',
    yinyang: '阴阳五行',
    ai: 'AI',
    homepage: '搭建网站',
    masters: '硕士论文',
    doctoral: '博士论文',
    visitYoutube: '观看视频',
    visitWebsite: '访问网站',
    downloadPdf: '下载 PDF',
    comingSoon: '即将推出',
    backToTop: '返回列表',
    readerDownloads: '下载原文',
    readerYoutube: '观看 YouTube ↗',
    readerPrev: '上一章',
    readerNext: '下一章',
    readerToc: '打开目录',
    dissertationDesc: '硕士及博士学位论文',
    papersDesc: '期刊及学术会议论文',
    booksDesc: '独著单行本',
    yinyangDesc: '阴阳五行相关研究与内容',
    aiDesc: 'AI 使用指南与实操资料',
    homepageDesc: '用 AI 搭建自己的网站的完整指南',
  },
  home: {
    heading: '陰陽五行',
    subheading: '崔元赫学术研究',
    intro: '研究东学思想与大巡思想的自生性近代性、循环经济观及阴阳五行的立体诠释。',
  },
  dissertation: {
    doctoral: [
      {
        id: 'doctoral-donghak-daesoon',
        title: '东学思想与大巡思想自生性近代性比较研究',
        subtitle: '博士学位论文',
        description: '比较分析东学思想与大巡思想内在自生性近代性的博士学位论文。',
        youtubeUrl: YOUTUBE,
        websiteUrl: '/zh/dissertation/doctoral/donghak-daesoon-zh',
      },
    ],
    masters: [
      {
        id: 'masters-daesoon-economy',
        title: '大巡思想的循环经济观',
        subtitle: '硕士学位论文',
        description: '研究大巡思想中经济思想循环特性的硕士学位论文。',
        youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN-qQKkJErG7QrrHCVobzg4X',
        websiteUrl: '/zh/dissertation/masters/daesoon-economics-zh',
      },
    ],
  },
  papers: [
    {
      id: 'paper-baekchongang',
      title: '663年白村江之战的东方天文学意义',
      subtitle: '会议论文',
      description: '本发表论文以三功能体系解读东方天文学，揭示作为最初甲子（癸亥年甲子月甲子日甲子时）的663年冬至五星聚娄现象与白村江之战所具有的天文学与历史意义。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLdy4e-DCK7iU',
      websiteUrl: '/zh/papers/baekgang-663',
    },
    {
      id: 'paper-search-for-dialogue',
      title: '在基督教与伊斯兰教之间寻求对话',
      subtitle: '会议论文',
      description: '本发表论文以阴阳五行为基础的大巡真理宗教循环论为依据，借助儒教与佛教为中介，探索基督教与伊斯兰教之间对话的可能性。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLem_5GS1xkbU',
      websiteUrl: '/zh/papers/search-for-dialogue',
    },
    {
      id: 'paper-jeju-myth-world',
      title: '作为世界神话的济州神话之可能性研究',
      subtitle: '会议论文',
      description: '本文以亚特兰蒂斯神话为中心，透过巽他古陆、《符都志》与君子国文献，探讨济州神话作为世界原型神话的可能性。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLIOWy1Be-8-k',
      websiteUrl: '/zh/papers/jeju-myth',
    },
    {
      id: 'paper-kim-jiha',
      title: '金芝河思想中的和解与相生研究',
      subtitle: '会议论文',
      description: '本文以阈限性与复活化解读金芝河思想的一贯性，比较从东学的生命思想、正易的律吕到甑山白荫（白色阴影）美学一脉相承的和解与相生脉络。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN9IghArp0ZbgUa-0Ld2YvxU',
      websiteUrl: '/zh/papers/kim-jiha',
    },
    {
      id: 'paper-dangun-economy',
      title: '作为经济思想的檀君思想与西方韩流',
      subtitle: '会议论文',
      description: '本文将韩流的道德背景与檀君思想相联系，通过弘益人间·在世理化的经济思想（三数分化·立体五行）与西方韩流的历史加以阐明。',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLw9IxWay4JN_Q3100PlwmezrKMLUyD01Q',
      websiteUrl: '/zh/papers/dangun-economy',
    },
    {
      id: 'papers-placeholder',
      title: '更多论文即将发布',
      subtitle: '敬请期待',
      comingSoon: true,
    },
  ],
  books: [
    {
      id: 'book-ai-survival',
      title: 'AI时代通过相关性思维与和诤的人类生存战略',
      subtitle: '单行本',
      description: '探讨人工智能时代人类生存战略的著作。',
      youtubeUrl: 'https://youtu.be/E1QaFGrYTY0',
      websiteUrl: '/zh/books/ai-survival',
    },
    {
      id: 'book-jeju-serendipity',
      title: '作为塞伦迪皮蒂的济州文化',
      subtitle: '单行本 · 济州学丛书 ⑨',
      description: '从塞伦迪皮蒂（将偶然引向成功的力量）的视角，探讨济州备受瞩目之理由的济州学研究著作。中文全译本，可在线阅读。（金德三·崔元爀 合著，2014年）',
      youtubeUrl: 'https://www.youtube.com/playlist?list=PLKq33i8Hqfjo',
      websiteUrl: '/zh/books/jeju-serendipity',
    },
  ],
  yinyang: [
    {
      id: 'yinyang-3d',
      title: '立体五行',
      subtitle: '阴阳五行',
      description: '关于阴阳五行立体诠释与现代应用的研究。',
      youtubeUrl: YOUTUBE,
    },
  ],
  ai: {
    homepage: [
      {
        id: 'ai-homepage-guide',
        title: '电脑小白也能上手的网站搭建六步完全指南(全本)',
        subtitle: 'AI · 搭建网站 · 全本',
        description: '从购买域名到配置 Vercel、GitHub、Obsidian、Google Drive,再到安装 Claude Code 并完成网站制作与部署,分六步整理的完整指南(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko.pdf',
        youtubeUrl: 'https://youtu.be/5L5IP7iyvko',
      },
      {
        id: 'ai-homepage-ch00',
        title: '00. 简介 · 全流程',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '先梳理网站搭建六步指南整体流程的入门章(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch00.pdf',
        youtubeUrl: 'https://youtu.be/qQfcldWYc-E',
      },
      {
        id: 'ai-homepage-ch01',
        title: '01. Whois · 域名购买',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '在 Whois 上搜索并购买自己的域名的分步指南(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch01.pdf',
      },
      {
        id: 'ai-homepage-ch02',
        title: '02. Vercel 注册',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '注册部署平台 Vercel 并完成初始设置的方法(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch02.pdf',
      },
      {
        id: 'ai-homepage-ch03',
        title: '03. GitHub 注册',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '注册源代码托管平台 GitHub 并准备仓库的方法(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch03.pdf',
      },
      {
        id: 'ai-homepage-ch04',
        title: '04. Obsidian 使用',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '笔记与写作工具 Obsidian 的安装与使用方法(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch04.pdf',
      },
      {
        id: 'ai-homepage-ch05',
        title: '05. Google Drive 使用',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '把 Google Drive 用作工作空间的方法(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch05.pdf',
      },
      {
        id: 'ai-homepage-ch06a',
        title: '06a. Claude Code 安装',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: 'Claude Code CLI 的安装与初次登录/认证流程(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch06a.pdf',
      },
      {
        id: 'ai-homepage-ch06b',
        title: '06b. Claude Code · 站点制作与部署',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '使用 Claude Code 制作实际站点并部署到 Vercel 的完整流程(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch06b.pdf',
      },
      {
        id: 'ai-homepage-ch07',
        title: '07. 附录 · 命令与费用',
        subtitle: 'AI · 搭建网站 · 分章指南',
        description: '整理常用命令与各服务费用的附录(韩文版)。',
        pdfUrl: '/pdf/website-guide-ko-ch07.pdf',
      },
    ],
  },
};
